In [3]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from facenet_pytorch import MTCNN
import os, cv2

In [5]:
device = torch.device("cuda:0" if torch.cuda.is_available() else "cpu") # device object
device

device(type='cuda', index=0)

In [21]:
mtcnn = MTCNN(keep_all=True, device=device)
new_img_dir = './input/data/train/cropped_images'
img_path = './input/data/train/images'

cnt = 0

for paths in os.listdir(img_path):
    if paths[0] == '.': continue
    
    sub_dir = os.path.join(img_path, paths)
    
    for imgs in os.listdir(sub_dir):
        if imgs[0] == '.': continue
        
        img_dir = os.path.join(sub_dir, imgs)
        img = cv2.imread(img_dir)
        img = cv2.cvtColor(img,cv2.COLOR_BGR2RGB)
        
        #mtcnn 적용
        boxes,probs = mtcnn.detect(img)
        
        # boxes 확인
        if len(probs) > 1: 
            print(boxes)
        if not isinstance(boxes, np.ndarray):
            print('Nope!')
            # 직접 crop
            img=img[100:400, 50:350, :]
        
        # boexes size 확인
        else:
            xmin = int(boxes[0, 0])-30
            ymin = int(boxes[0, 1])-30
            xmax = int(boxes[0, 2])+30
            ymax = int(boxes[0, 3])+30
            
            if xmin < 0: xmin = 0
            if ymin < 0: ymin = 0
            if xmax > 384: xmax = 384
            if ymax > 512: ymax = 512
            
            img = img[ymin:ymax, xmin:xmax, :]
        
        n_path = os.path.join(paths, imgs).replace('/', '_')
        cnt += 1
        print(os.path.join(new_img_dir, n_path))
        plt.imsave(os.path.join(new_img_dir, n_path), img)
        
print(cnt)

./input/data/train/cropped_images/003885_female_Asian_52_mask3.jpg
./input/data/train/cropped_images/003885_female_Asian_52_mask5.jpg
./input/data/train/cropped_images/003885_female_Asian_52_normal.jpg
./input/data/train/cropped_images/003885_female_Asian_52_incorrect_mask.jpg
./input/data/train/cropped_images/003885_female_Asian_52_mask2.jpg
./input/data/train/cropped_images/003885_female_Asian_52_mask1.jpg
./input/data/train/cropped_images/003885_female_Asian_52_mask4.jpg
./input/data/train/cropped_images/001014_male_Asian_19_mask3.jpg
./input/data/train/cropped_images/001014_male_Asian_19_mask5.jpg
./input/data/train/cropped_images/001014_male_Asian_19_normal.jpg
./input/data/train/cropped_images/001014_male_Asian_19_incorrect_mask.jpg
[[114.605515 240.96587  281.13464  416.53223 ]
 [114.011505 130.2351   261.82626  310.00684 ]]
./input/data/train/cropped_images/001014_male_Asian_19_mask2.jpg
./input/data/train/cropped_images/001014_male_Asian_19_mask1.jpg
./input/data/train/cropped

In [22]:
mtcnn = MTCNN(keep_all=True, device=device)
new_img_dir = './input/data/eval/cropped_images'
img_path = './input/data/eval/images'

cnt = 0
    
for imgs in os.listdir(img_path):
    if imgs[0] == '.': continue

    img_dir = os.path.join(img_path, imgs)
    img = cv2.imread(img_dir)
    img = cv2.cvtColor(img,cv2.COLOR_BGR2RGB)

    #mtcnn 적용
    boxes,probs = mtcnn.detect(img)

    # boxes 확인
    if len(probs) > 1: 
        print(boxes)
    if not isinstance(boxes, np.ndarray):
        print('Nope!')
        # 직접 crop
        img=img[100:400, 50:350, :]

    # boexes size 확인
    else:
        xmin = int(boxes[0, 0])-30
        ymin = int(boxes[0, 1])-30
        xmax = int(boxes[0, 2])+30
        ymax = int(boxes[0, 3])+30

        if xmin < 0: xmin = 0
        if ymin < 0: ymin = 0
        if xmax > 384: xmax = 384
        if ymax > 512: ymax = 512

        img = img[ymin:ymax, xmin:xmax, :]

    cnt += 1
    plt.imsave(os.path.join(new_img_dir, imgs), img)
        
print(cnt)

[[108.02834 170.00438 279.6733  391.03415]
 [147.91655 376.83447 221.65874 448.05478]]
[[ 94.371475  123.40232   268.37473   353.40002  ]
 [ -5.4433947 255.14609    11.624443  277.92538  ]]
Nope!
[[ 96.575775 128.391    324.3775   403.79398 ]
 [ 88.187195 432.4481   120.39852  473.15085 ]]
[[104.96323 130.0998  311.99872 394.66165]
 [152.47556  81.92514 243.75148 187.81073]]
[[105.14317  127.57512  285.08414  356.96875 ]
 [ 14.687613 231.23315   38.745235 260.7409  ]]
Nope!
[[ 82.93485   54.173523 318.6801   346.26245 ]
 [-12.282314 126.217026   9.982567 153.74838 ]]
[[ 85.41234  140.29515  265.3252   358.40625 ]
 [ 43.886944 207.90224   69.52365  238.59439 ]]
[[ 97.07181 162.89864 288.9322  388.01935]
 [186.94867 396.05606 270.94064 490.98325]]
[[107.157074 137.31618  286.65308  387.82755 ]
 [ 82.90579  354.83783  105.44848  384.23135 ]]
[[102.866   117.05483 261.14713 333.13928]
 [326.56454 201.83035 360.01834 248.97922]]
[[123.13185 163.93182 255.13133 329.1771 ]
 [157.50006 324.028

# Save cropped dataframe as csv file

In [47]:
data_dir = 'input/data/train'
df_path = f'{data_dir}/new_train.csv'
cropped_df_path = f'{data_dir}/cropped_train.csv'

In [51]:
df = pd.read_csv(df_path)
df

Unnamed: 0            gender race age isWearing  \
0               0  female Asian 45 incorrectly wearing   
1               1              female Asian 45 wearing   
2               2              female Asian 45 wearing   
3               3              female Asian 45 wearing   
4               4              female Asian 45 wearing   
...           ...                                  ...   
18894       18894                male Asian 19 wearing   
18895       18895                male Asian 19 wearing   
18896       18896                male Asian 19 wearing   
18897       18897                male Asian 19 wearing   
18898       18898            male Asian 19 not wearing   

                                                abs_path  class  
0      input/data/train/images/000001_female_Asian_45...     10  
1      input/data/train/images/000001_female_Asian_45...      4  
2      input/data/train/images/000001_female_Asian_45...      4  
3      input/data/train/images/000001_female_Asian_45...      4  
4      input/data/train/images/000001_female_Asian_45...      4  
...                                                  ...    ...  
18894  input/data/train/images/006959_male_Asian_19/m...      0  
18895  input/data/train/images/006959_male_Asian_19/m...      0  
18896  input/data/train/images/006959_male_Asian_19/m...      0  
18897  input/data/train/images/006959_male_Asian_19/m...      0  
18898  input/data/train/images/006959_male_Asian_19/n...     12  

[18899 rows x 4 columns]

In [54]:
for i in range(len(df)):
    path = df.iloc[i]["abs_path"].replace('images', 'cropped_images')
    tmp_path = path[32:].replace('/', '_')
    path = path[:32] + tmp_path
    df.loc[i, "abs_path"] = path

df.head()

Unnamed: 0            gender race age isWearing  \
0           0  female Asian 45 incorrectly wearing   
1           1              female Asian 45 wearing   
2           2              female Asian 45 wearing   
3           3              female Asian 45 wearing   
4           4              female Asian 45 wearing   

                                            abs_path  class  
0  input/data/train/cropped_images/000001_female_...     10  
1  input/data/train/cropped_images/000001_female_...      4  
2  input/data/train/cropped_images/000001_female_...      4  
3  input/data/train/cropped_images/000001_female_...      4  
4  input/data/train/cropped_images/000001_female_...      4

In [55]:
df.to_csv(cropped_df_path)